#!/usr/bin/env python3
"""Generate llms.txt from the trigger index and the domain files.

The index is already the shape llms.txt asks for — a list of links with notes
— so this is a transformation, not an invention. Each domain becomes an H2
section; each gotcha becomes a link into its file's anchor, annotated with the
trigger that tells an agent when the entry is worth loading.

Format follows https://llmstxt.org: an H1 (the only required section), a
blockquote summary, then H2-delimited file lists of `- [name](url): notes`.
An "Optional" section holds links an agent can skip for a shorter context.

The parsers are imported from the contract script rather than reimplemented:
two copies of "what counts as an entry" would drift, and the contract is the
side that must win.

Usage:
    python3 scripts/gen-llms-txt.py            # write llms.txt
    python3 scripts/gen-llms-txt.py --check    # exit 1 if it would change

Stdlib only. Python 3.11+.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("contract", HERE / "assert-agent-workflow.py")
contract = importlib.util.module_from_spec(_spec)
assert _spec.loader is not None
# Register before executing: the contract module uses `from __future__ import
# annotations`, so @dataclass resolves its field types as strings by looking
# the module up in sys.modules. Without this it raises AttributeError on None.
sys.modules["contract"] = contract
_spec.loader.exec_module(contract)

OUTPUT = "llms.txt"
GENERATED_NOTE = "Generated by scripts/gen-llms-txt.py — run it rather than editing this file."


def anchor(title: str) -> str:
    """GitHub's heading slug: lowercase, punctuation dropped, spaces hyphenated."""
    slug = title.lower()
    slug = slug.replace("—", "").replace("–", "")
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"[\s_]+", "-", slug.strip()).strip("-")


def render(root: Path, cfg: contract.Config) -> str:
    index, errors = contract.parse_index(
        contract.read_text(root / cfg.contract), cfg.heading
    )
    if errors:
        raise SystemExit(
            "refusing to generate from an index that does not parse:\n  "
            + "\n  ".join(errors)
        )

    sections: list[str] = []
    total = 0

    for fname, bullets in index.items():
        path = root / cfg.gotchas / fname
        text = contract.read_text(path)
        meta = contract.parse_frontmatter(text)
        titles = [title for title, _ in contract.parse_entries(text)]
        total += len(titles)

        rel = f"{cfg.gotchas}/{fname}"
        lines = [f"## {meta.get('domain', fname)}", ""]
        if meta.get("triggers"):
            lines.append(f"Read when touching {meta['triggers']}. Updated {meta.get('updated', 'unknown')}.")
            lines.append("")

        # The bullet carries the annotation the title does not; prefer it as notes.
        notes = {contract.ANNOTATION_RE.sub("", b): b for b in bullets}
        for title in titles:
            note = notes.get(title, title)
            suffix = note[len(title):].strip() if note.startswith(title) else ""
            entry = f"- [{title}]({rel}#{anchor(title)})"
            lines.append(f"{entry}: {suffix}" if suffix else entry)
        sections.append("\n".join(lines))

    optional: list[str] = []
    pdir = root / cfg.postmortems
    if pdir.is_dir():
        files = sorted(p for p in pdir.glob("*.md") if p.name != "README.md")
        if files:
            optional = [
                "## Optional",
                "",
                "Full incident narratives. The gotchas above carry the lesson; these carry the story.",
                "",
                *[f"- [{p.stem}]({cfg.postmortems}/{p.name})" for p in files],
            ]

    header = [
        f"# {cfg.name or root.name} — gotchas",
        "",
        f"> {total} gotchas across {len(index)} domain "
        f"{'file' if len(index) == 1 else 'files'}, each earned by a break or a near-miss.",
        f"> Every entry is indexed in {cfg.contract} and loaded only when its trigger matches.",
        f"> {GENERATED_NOTE}",
        "",
    ]
    return "\n".join(header + ["\n".join(sections)] + ([""] + optional if optional else [])).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file differs from a fresh generation")
    args = parser.parse_args()

    root = (args.root or contract.find_root(Path.cwd())).resolve()
    generated = render(root, contract.load_config(root))
    target = root / OUTPUT

    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != generated:
            print(f"{OUTPUT} is stale — run: python3 scripts/gen-llms-txt.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date.")
        return 0

    target.write_text(generated, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(generated.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
